### PR TITLE
node-aab-parser updated

### LINKED ISSUE #46: Update node-aab-parser dependency and publish to npm
@nprail node-aab-parser has been updated so that its dependency, bundletool has been updated to include binary caching, please update and publish!

### PR DESCRIPTION
**Pull request by jpike88**
updated node-aab-parser, fixes #46

### CODE REVIEW

**Review by nprail — APPROVED** [review]

**Comment by jpike88** [comment]
@nprail thanks for the merge, do you plan on publishing a new npm version soon?

**Comment by nprail** [comment]
Yep, I am working on that right now 🙂

**Comment by jpike88** [comment]
legend 👍

**Pull request merged**
